# Generated by Django 3.2.3 on 2021-05-24 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Threads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('date_time', models.DateTimeField(max_length=18)),
                ('replies', models.CharField(max_length=5000)),
                ('url', models.CharField(max_length=200, unique=True)),
                ('title', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('date_time', models.DateTimeField()),
                ('score', models.DecimalField(decimal_places=4, max_digits=6)),
                ('quoted', models.CharField(max_length=8)),
                ('sentiment', models.CharField(max_length=10)),
                ('replies', models.CharField(max_length=10000)),
                ('thread_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.threads')),
            ],
        ),
        migrations.AddConstraint(
            model_name='posts',
            constraint=models.UniqueConstraint(fields=('username', 'date_time'), name='composite_key'),
        ),
    ]
